// example-base-03/angular-crud/src/app/student/student.component.ts
// src/app/student/student.component.ts
import { Component, OnInit } from '@angular/core';
import { StudentService } from './student.service';

interface Student {
  id: number;
  name: string;
  age: number;
}

@Component({
  selector: 'app-student',
  templateUrl: './student.component.html',
  styleUrls: ['./student.component.css']
})
export class StudentComponent implements OnInit {
  students: Student[] = [];
  newStudent: Student = { id: 0, name: '', age: 0 };
  editStudent: Student | null = null;

  constructor(private studentService: StudentService) {}

  ngOnInit(): void {
    this.loadStudents();
  }

  loadStudents(): void {
    this.studentService.getStudents().subscribe((data: Student[]) => {
      this.students = data;
    });
  }

  addStudent(): void {
    this.studentService.createStudent(this.newStudent).subscribe((student: Student) => {
      this.students.push(student);
      this.newStudent = { id: 0, name: '', age: 0 };
    });
  }

  updateStudent(): void {
    if (this.editStudent) {
      this.studentService.updateStudent(this.editStudent.id, this.editStudent).subscribe(() => {
        this.loadStudents();
        this.editStudent = null;
      });
    }
  }

  deleteStudent(id: number): void {
    this.studentService.deleteStudent(id).subscribe(() => {
      this.loadStudents();
    });
  }

  edit(student: Student): void {
    this.editStudent = { ...student };
  }

  cancelEdit(): void {
    this.editStudent = null;
  }
}

<!-- src/app/student/student.component.html -->
<div>
    <h1>Student List</h1>
    <ul>
      <li *ngFor="let student of students">
        {{ student.name }} ({{ student.age }}) 
        <button (click)="edit(student)">Edit</button>
        <button (click)="deleteStudent(student.id)">Delete</button>
      </li>
    </ul>
  
    <h2>Add New Student</h2>
    <form (ngSubmit)="addStudent()">
      <input [(ngModel)]="newStudent.name" name="name" placeholder="Name" required>
      <input [(ngModel)]="newStudent.age" name="age" type="number" placeholder="Age" required>
      <button type="submit">Add</button>
    </form>
  
    <div *ngIf="editStudent">
      <h2>Edit Student</h2>
      <form (ngSubmit)="updateStudent()">
        <input [(ngModel)]="editStudent.name" name="editName" placeholder="Name" required>
        <input [(ngModel)]="editStudent.age" name="editAge" type="number" placeholder="Age" required>
        <button type="submit">Update</button>
        <button type="button" (click)="cancelEdit()">Cancel</button>
      </form>
    </div>
  </div>

// example-base-03/vue-crud/src/components/StudentComponent.vue
<!-- src/components/StudentComponent.vue -->
<template>
    <div>
      <h1>Student List</h1>
      <ul>
        <li v-for="student in students" :key="student.id">
          {{ student.name }} ({{ student.age }})
          <button @click="edit(student)">Edit</button>
          <button @click="deleteStudent(student.id)">Delete</button>
        </li>
      </ul>
  
      <h2>Add New Student</h2>
      <form @submit.prevent="addStudent">
        <input v-model="newStudent.name" placeholder="Name" required>
        <input v-model="newStudent.age" type="number" placeholder="Age" required>
        <button type="submit">Add</button>
      </form>
  
      <div v-if="editStudent">
        <h2>Edit Student</h2>
        <form @submit.prevent="updateStudent">
          <input v-model="editStudent.name" placeholder="Name" required>
          <input v-model="editStudent.age" type="number" placeholder="Age" required>
          <button type="submit">Update</button>
          <button @click="cancelEdit">Cancel</button>
        </form>
      </div>
    </div>
  </template>
  
  <script>
  import axios from 'axios';
  
  export default {
    data() {
      return {
        students: [],
        newStudent: { id: 0, name: '', age: 0 },
        editStudent: null,
      };
    },
    methods: {
      loadStudents() {
        axios.get('http://localhost:3000/students').then(response => {
          this.students = response.data;
        });
      },
      addStudent() {
        axios.post('http://localhost:3000/students', this.newStudent).then(response => {
          this.students.push(response.data);
          this.newStudent = { id: 0, name: '', age: 0 };
        });
      },
      updateStudent() {
        axios.put(`http://localhost:3000/students/${this.editStudent.id}`, this.editStudent).then(() => {
          this.loadStudents();
          this.editStudent = null;
        });
      },
      deleteStudent(id) {
        axios.delete(`http://localhost:3000/students/${id}`).then(() => {
          this.loadStudents();
        });
      },
      edit(student) {
        this.editStudent = { ...student };
      },
      cancelEdit() {
        this.editStudent = null;
      },
    },
    mounted() {
      this.loadStudents();
    },
  };
  </script>
  
  <style scoped>
  /* Add your styles here */
  </style>
