// example-base-05/md-markdown-viewer-angular/src/app/components/file-sidebar/file-sidebar.component.ts
import { Component, Input, Output, EventEmitter, OnInit, ElementRef, ViewChild, AfterViewChecked } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MarkdownFile } from '../../models/markdown-file.model';

@Component({
  selector: 'app-file-sidebar',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './file-sidebar.component.html',
  styleUrls: ['./file-sidebar.component.css']
})
export class FileSidebarComponent implements OnInit, AfterViewChecked {
  @Input() files: MarkdownFile[] = [];
  @Input() activeFile: MarkdownFile | null = null;
  @Input() sidebarOpen: boolean = true;
  @Output() fileSelected = new EventEmitter<string>();
  @Output() sidebarToggle = new EventEmitter<void>();

  filter: string = '';
  private shouldScroll: boolean = false;

  @ViewChild('sidebarList', { static: false }) sidebarList!: ElementRef;

  get filteredFiles(): MarkdownFile[] {
    if (!this.filter.trim()) {
      return this.files;
    }
    const query = this.filter.toLowerCase();
    return this.files.filter(file =>
      file.name.toLowerCase().includes(query) ||
      file.relativePath.toLowerCase().includes(query)
    );
  }

  ngOnInit(): void {}

  ngAfterViewChecked(): void {
    if (this.shouldScroll && this.activeFile) {
      this.scrollToActiveFile();
      this.shouldScroll = false;
    }
  }

  onFileClick(slug: string): void {
    this.shouldScroll = true;
    this.fileSelected.emit(slug);
  }

  private scrollToActiveFile(): void {
    if (!this.activeFile || !this.sidebarList) {
      return;
    }

    const activeItem = this.sidebarList.nativeElement.querySelector(`[data-slug="${this.activeFile.slug}"]`);
    if (activeItem) {
      activeItem.scrollIntoView({ block: 'center', behavior: 'smooth' });
    }
  }

  isActive(file: MarkdownFile): boolean {
    return this.activeFile?.slug === file.slug;
  }

  trackBySlug(index: number, file: MarkdownFile): string {
    return file.slug;
  }
}

<aside
  *ngIf="sidebarOpen"
  class="border-end border-secondary bg-dark text-light overflow-hidden d-flex flex-column h-100"
>
  <div class="p-3 d-flex flex-column flex-grow-1 overflow-hidden">
    <div class="mb-3 flex-shrink-0">
      <label class="form-label text-uppercase text-muted small">Quick filter</label>
      <input
        type="search"
        class="form-control form-control-sm bg-dark border-secondary text-light"
        placeholder="Type to filter..."
        [(ngModel)]="filter"
      />
    </div>

    <div
      #sidebarList
      class="list-group list-group-flush flex-grow-1 overflow-auto"
    >
      <button
        *ngFor="let file of filteredFiles; trackBy: trackBySlug"
        type="button"
        class="list-group-item list-group-item-action bg-dark border-secondary text-light"
        [class.active]="isActive(file)"
        [attr.data-slug]="file.slug"
        (click)="onFileClick(file.slug)"
      >
        <p class="fw-semibold mb-1">{{ file.name }}</p>
        <small class="text-muted d-block text-truncate">{{ file.relativePath }}</small>
      </button>
      <div
        *ngIf="filteredFiles.length === 0"
        class="list-group-item bg-dark border-secondary text-muted text-center py-4"
      >
        No files match your filter
      </div>
      <div
        *ngIf="files.length === 0"
        class="list-group-item bg-dark border-secondary text-muted text-center py-4"
      >
        No markdown files found
      </div>
    </div>
  </div>
</aside>

// example-base-05/md-markdown-viewer-client/src/components/FileSidebar.tsx
import type { MarkdownFileMeta } from '../types';
import clsx from 'clsx';
import { useEffect, useRef } from 'react';

interface FileSidebarProps {
  files: MarkdownFileMeta[];
  activeSlug: string | null;
  filter: string;
  onFilterChange: (value: string) => void;
  onSelect: (slug: string) => void;
}

export function FileSidebar({ files, activeSlug, filter, onFilterChange, onSelect }: FileSidebarProps) {
  const normalizedFilter = filter.toLowerCase();
  const filtered = normalizedFilter
    ? files.filter((file) => `${file.name} ${file.relativePath}`.toLowerCase().includes(normalizedFilter))
    : files;

  const activeRef = useRef<HTMLButtonElement | null>(null);

  useEffect(() => {
    const node = activeRef.current;
    if (node) {
      node.scrollIntoView({ block: 'center', behavior: 'smooth' });
    }
  }, [activeSlug, filtered.length]);

  return (
    <div className="sidebar-panel h-100 d-flex flex-column">
      <div className="d-flex justify-content-between align-items-center border-bottom border-secondary px-4 py-3">
        <div>
          <p className="text-uppercase text-muted small mb-0">Markdown files</p>
          <small className="text-muted">{files.length} total</small>
        </div>
      </div>

      <div className="p-4 pt-3 flex-grow-1 d-flex flex-column">
        <div className="mb-3">
          <label className="form-label text-uppercase text-muted small">Quick filter</label>
          <input
            value={filter}
            onChange={(event) => onFilterChange(event.target.value)}
            type="search"
            placeholder="Type to filter..."
            className="form-control form-control-sm bg-dark text-light border-secondary"
          />
        </div>

        <div className="sidebar-scroll scroll-y flex-grow-1">
          <div className="list-group list-group-flush">
            {filtered.map((file) => {
              const isActive = file.slug === activeSlug;
              return (
                <button
                  key={file.slug}
                  type="button"
                  ref={isActive ? activeRef : null}
                  onClick={() => onSelect(file.slug)}
                  className={clsx(
                    'list-group-item list-group-item-action bg-transparent text-start text-light border-secondary-subtle',
                    isActive && 'active'
                  )}
                >
                  <div className="fw-semibold">{file.name}</div>
                  <small className="text-muted d-block text-truncate">{file.relativePath}</small>
                </button>
              );
            })}
            {!files.length && (
              <div className="list-group-item bg-transparent text-muted">
                No markdown files found. Check API connectivity.
              </div>
            )}
            {files.length > 0 && !filtered.length && (
              <div className="list-group-item bg-transparent text-muted">Nothing matches “{filter}”.</div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
