// example-base-05/vocab-khajana-nextjs/src/components/WordCard.tsx
import { WordEntry } from "@/lib/khajana";

interface WordCardProps {
  entry: WordEntry;
}

export function WordCard({ entry }: WordCardProps) {
  return (
    <article className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm transition hover:border-slate-300 hover:shadow-md focus-within:border-blue-500 focus-within:shadow-lg dark:border-slate-700 dark:bg-slate-900 dark:hover:border-slate-600 dark:hover:shadow-blue-900/20">
      <header className="mb-4 flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2">
        <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100">
          {entry.word}
        </h2>
        {entry.type ? (
          <span className="inline-flex items-center rounded-full bg-blue-100 px-3 py-1 text-xs font-medium uppercase tracking-wide text-blue-700 dark:bg-blue-500/20 dark:text-blue-200">
            {entry.type}
          </span>
        ) : null}
      </header>

      {entry.meanings.length > 0 ? (
        <section aria-label="Meanings" className="mb-4 space-y-1">
          {entry.meanings.map((meaning, index) => (
            <p key={index} className="text-sm text-slate-700 dark:text-slate-200">
              {meaning}
            </p>
          ))}
        </section>
      ) : null}

      {entry.examples.length > 0 ? (
        <section aria-label="Examples" className="space-y-2">
          <h3 className="text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
            Examples
          </h3>
          <ul className="list-disc space-y-1 pl-5 text-sm text-slate-600 dark:text-slate-300">
            {entry.examples.map((example, index) => (
              <li key={index}>{example}</li>
            ))}
          </ul>
        </section>
      ) : null}
    </article>
  );
}

// example-base-05/vocab-khajana-vuejs/src/components/WordCard.vue
<template>
  <article
    class="flex h-full flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:border-slate-700 dark:bg-slate-800 dark:shadow-lg/20"
  >
    <header class="flex items-start justify-between gap-4">
      <h2 class="text-xl font-semibold text-slate-900 dark:text-slate-100">{{ entry.word }}</h2>
      <span
        v-if="entry.type"
        class="rounded-full bg-indigo-100 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-indigo-700 dark:bg-indigo-500/20 dark:text-indigo-200"
      >
        {{ entry.type }}
      </span>
    </header>

    <section v-if="entry.meanings.length" class="space-y-2">
      <h3 class="text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">Meanings</h3>
      <ul class="list-disc space-y-2 pl-5 text-sm text-slate-700 dark:text-slate-200">
        <li v-for="meaning in entry.meanings" :key="meaning">{{ meaning }}</li>
      </ul>
    </section>

    <section v-if="entry.examples.length" class="space-y-2">
      <h3 class="text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">Examples</h3>
      <ul class="space-y-3 text-sm text-slate-600 dark:text-slate-300">
        <li v-for="example in entry.examples" :key="example">
          <blockquote class="border-l-2 border-indigo-200 pl-3 italic text-slate-700 dark:border-indigo-500/30 dark:text-slate-200">
            {{ example }}
          </blockquote>
        </li>
      </ul>
    </section>
  </article>
</template>

<script setup lang="ts">
import type { WordEntry } from '@/types';

defineProps<{
  entry: WordEntry;
}>();
</script>
